export class BikeEvent {
    eventDate: Date;
    detail: string;
    autoGenerated: boolean;
    isPrivate: boolean;
    type: string;

    constructor(eventDate: Date, detail: string, autoGenerated: boolean, isPrivate: boolean, type: string) {
        this.eventDate = eventDate;
        this.detail = detail;
        this.autoGenerated = autoGenerated;
        this.isPrivate = isPrivate;
        this.type = type;
    }
}
